extends: schibsted
env:
    node: true
    mocha: true
rules:
    no-undefined: off
    no-var: off
    no-unused-vars:
      - error
      - argsIgnorePattern: next
    require-jsdoc:
      - warn
    valid-jsdoc:
      - error
      - requireParamDescription: false
        requireReturnDescription: false
    max-nested-callbacks:
      - error
      - 4
    camelcase: off
