language: node_js
sudo: false
node_js:
- '6'
- '7'
cache:
  directories:
  - node_modules # cache NPM modules to make the build faster
install: npm install
script: npm test
deploy:
  on:
    tags: true
    branch: master
  provider: npm
  api_key:
    secure: SZRNowaJfM0H21ScTmYGz6/WuJ76TySC8prh/kQGfsoTqC8lCpz0Z7+tXstt61Pe7kOj3tHtoki7AnqxfuqnNQclpp9wheA8trziSBevPcghxpZppaftT0buJHaV3w1JFFEkU/U1Hpr0gLrxym4LeC5Q+1aMoViDFvhTR+i4fEZCQtNj5nh1Gm6DtQ5AYHOuqmN+ucNOU7hVU/OvSU8xdhP7Jyq1ymqwzSvFiELo7Sj9wc5pc4frq8XfqTAAfTaRhbeYYqsEp6qwRTHdM1Wo37mKjAaNZ7nX1ZzLjRv1jgqA+YIIXvkA5peh5Ms5ARx3Quus6AlCtJPLPp6Jrz+XFqZN5JghMRpLrPdzmUD1nirT+qPscSQAObBEbBL8aEcAVqekcIB2u2WaaeWbSzmi3IMCn9mG6TmtWjTdIwzDRj3ocFoPYRCpeCU4ZmfidfbT4Vyae5hrNwHIRaqP5dD4qTQPW220Pk0yzE1xgY6h5HVIJsYoihG+RkqGrRgECIG/JyTWFnoOKxANs0EawuQPN8Ijcnnlv4jzEghX/p3Nw1SGDdpW0XxhrcRxPLFBYXwkGxHsOA9+J/2IzW4STW6o33w4TBe3cSHaZ1b5DSyNIAIzG3m1Qj3FlJMrNIT31Kn4zzLjWDv0O2NSapllupSMb9abCAHUyx8A24IYihiJgJw=
